---

openapi: 3.0.0
info:
  title: Simple Key-Value Storage API
  description: A simple REST API for key-value storage with CRUD operations.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

paths:
  /store:
    post:
      summary: Create a new key-value pair
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - key
                - value
              properties:
                key:
                  type: string
                  example: "example_key"
                value:
                  type: string
                  example: "example_value"
      responses:
        "201":
          description: Key-value pair created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Key-value pair created successfully"
                  key:
                    type: string
                    example: "example_key"
                  value:
                    type: string
                    example: "example_value"
        "400":
          description: Bad Request - Key already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Key already exists"

  /store/{key}:
    get:
      summary: Retrieve the value associated with the given key
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          example: "example_key"
      responses:
        "200":
          description: Value retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                    example: "example_key"
                  value:
                    type: string
                    example: "example_value"
        "404":
          description: Key not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Key not found"

    put:
      summary: Update the value associated with the given key
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          example: "example_key"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - value
              properties:
                value:
                  type: string
                  example: "new_value"
      responses:
        "200":
          description: Key-value pair updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Key-value pair updated successfully"
                  key:
                    type: string
                    example: "example_key"
                  value:
                    type: string
                    example: "new_value"
        "404":
          description: Key not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Key not found"

    delete:
      summary: Delete the key-value pair associated with the given key
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          example: "example_key"
      responses:
        "200":
          description: Key-value pair deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Key-value pair deleted successfully"
                  key:
                    type: string
                    example: "example_key"
        "404":
          description: Key not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Key not found"
